### ISSUE TITLE
OpenTofu Runner API access fails with 401 unauthorized

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-providers-embedded_terraform#49]
When hitting the opentofu-runner internal API the response is `401 Unauthorized`
```
#<Terraform::Runner::Response:0x00007f94dcb031c8
 @action=nil,
 @created_at=nil,
 @details=nil,
 @error_message=nil,
 @message="You do not have the necessary credentials.",
 @stack_id=nil,
 @stack_job_end_time=nil,
 @stack_job_start_time=nil,
 @stack_name=nil,
 @status=401>
```

**Comment by putmanoj** [comment]
@agrare 
 
At present, the auth in terraform-runner is based on env var `SECRET_KEY`  (default value is 'test') ,  which is used for the signed JWT token,
any JWT token signed with the  `SECRET_KEY`  should allow authentication.

**Comment by putmanoj** [comment]
Random secret key needs to be generated, used in `SECRET_KEY`  for opentofu-runner
and in embedded_terraform plugin,  `TERRAFORM_RUNNER_TOKEN`  will have signed JWT token, signed with `SECRET_KEY`.

---
any token, for example, you could simply use any one of these online tools 
http://jwtbuilder.jamiekurtz.com/ 
 https://www.javainuse.com/jwtgenerator

**Comment by agrare** [comment]
Fixed by https://github.com/ManageIQ/manageiq-providers-embedded_terraform/pull/56
